name: Build and Release Android APK

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g. v1.0.0)'
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push tag and create release

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to push tags

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK (with NDK)
        run: ./gradlew assembleDebug

      - name: Show built APKs
        run: find app/build/outputs/apk -name "*.apk"

      - name: Create Git tag ${{ inputs.release_tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ inputs.release_tag }}
          git push origin ${{ inputs.release_tag }}

      - name: Upload APKs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.release_tag }}
          name: Release ${{ inputs.release_tag }}
          generate_release_notes: true
          files: app/build/outputs/apk/**/*.apk
